services:
  mongo:
    image: mongo:8.0
    container_name: mongodb_hospital_api
    restart: always
    environment:
      MONGO_INITDB_ROOT_USERNAME: chheun
      MONGO_INITDB_ROOT_PASSWORD: chheun^^1223 
      MONGO_INITDB_DATABASE: hospital_nosql
    ports:
      - "27018:27017"
    volumes:
      - mongo_data:/data/db
    healthcheck:
      test: ["CMD", "mongosh", "--eval", "db.adminCommand('ping')"]
      interval: 10s
      timeout: 5s
      retries: 5

volumes:
  mongo_data:

# mongosh -u cheun -p "chheun^^1223" --authenticationDatabase admin "mongodb://127.0.0.1:27018/hospital_nosql"